### ISSUE TITLE
no main manifest attribute, in Evolving-Protozoa.jar

### ISSUE THREAD

**Issue by MtNoot** [DylanCope/Evolving-Protozoa#7]
getting the error "no main manifest attribute, in Evolving-Protozoa.jar" for v0.1.3 

also while i'm here the link in the readme is for java 8 and this program seems to need java 9 or above, idk anything about programming though so i could be mistaken.

**Comment by DylanCope** [comment]
Thank you for raising the issue - turns out I uploaded the wrong zip file! If you redownload it now it should work :)
